#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

app="[Desktop Entry]\nType=Application\nName=RedAsist\nComment=Redmine Asistant\nExec=$dir/redassist\nIcon=$dir/icon.png\nCategories=Office,Utility;"

applet="[Desktop Entry]\nType=Application\nName=RedAssist Applet\nExec=$dir/applet"

echo -e $app > /usr/share/applications/redassist.desktop
chmod +x /usr/share/applications/redassist.desktop
echo -e $applet > /etc/xdg/autostart/redassistApplet.desktop
chmod +x /etc/xdg/autostart/redassistApplet.desktop